"""
report_generator.py — Generate a multi-page PDF hiring report using fpdf2
"""
import io
from datetime import datetime


def generate_pdf_report(data: dict) -> bytes:
    """
    Generate a professional PDF hiring report.
    `data` dict keys:
        candidate_name, job_title, ai_score, skill_match_percent,
        prediction, selection_prob, matched_skills, missing_skills,
        recommendations, interview_questions, experience_years,
        education, bert_score, tfidf_score, bias_flags
    Returns PDF bytes.
    """
    try:
        from fpdf import FPDF, XPos, YPos

        class HirePDF(FPDF):
            def header(self):
                self.set_fill_color(15, 17, 23)
                self.rect(0, 0, 210, 18, "F")
                self.set_font("Helvetica", "B", 13)
                self.set_text_color(99, 179, 237)
                self.cell(0, 12, "SmartHire AI — Hiring Intelligence Report",
                          align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            def footer(self):
                self.set_y(-12)
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(150, 150, 150)
                self.cell(0, 10,
                          f"Generated by SmartHire AI  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  Page {self.page_no()}",
                          align="C")

        pdf = HirePDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # ── Title Section ──────────────────────────────────────────────
        pdf.set_fill_color(28, 31, 46)
        pdf.rect(10, 20, 190, 28, "F")
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(255, 255, 255)
        pdf.set_xy(14, 24)
        cname = data.get("candidate_name", "Candidate")
        pdf.cell(0, 8, f"Candidate: {cname}")
        pdf.set_xy(14, 33)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(180, 190, 210)
        role = data.get("job_title", "Applied Role")
        pdf.cell(0, 7, f"Role Applied: {role}")
        pdf.ln(20)

        # ── Score Summary ──────────────────────────────────────────────
        def section_header(title: str):
            pdf.set_fill_color(30, 40, 70)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(99, 179, 237)
            pdf.cell(0, 8, f"  {title}", fill=True,
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(2)

        def kv_row(label: str, value: str, alt: bool = False):
            pdf.set_fill_color(22, 27, 42) if alt else pdf.set_fill_color(18, 22, 36)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(180, 190, 210)
            pdf.cell(80, 7, f"  {label}", fill=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(230, 230, 230)
            pdf.cell(110, 7, f"  {value}", fill=True,
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        section_header("📊  Candidate Score Summary")
        ai_score = data.get("ai_score", 0)
        sel_prob = data.get("selection_prob", 0)
        prediction = data.get("prediction", "N/A")
        skill_match = data.get("skill_match_percent", 0)
        bert_score = data.get("bert_score", 0)

        kv_row("AI Score", f"{ai_score}/100", False)
        kv_row("Selection Probability", f"{round(sel_prob * 100, 1)}%", True)
        kv_row("Hiring Prediction", str(prediction), False)
        kv_row("Skill Match %", f"{skill_match}%", True)
        kv_row("BERT Semantic Score", f"{round(bert_score * 100, 1)}%", False)
        kv_row("Experience (Years)", str(data.get("experience_years", "N/A")), True)
        kv_row("Education", str(data.get("education", "N/A")), False)
        pdf.ln(5)

        # ── Skill Analysis ─────────────────────────────────────────────
        section_header("🛠️  Skill Analysis")

        def skill_list(label: str, skills: list, color):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*color)
            pdf.cell(0, 6, f"  {label}:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(210, 210, 210)
            skill_text = ", ".join(skills) if skills else "None"
            pdf.multi_cell(0, 5, f"  {skill_text}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(2)

        skill_list("Matched Skills ✓", data.get("matched_skills", []), (80, 200, 120))
        skill_list("Missing Skills ✗", data.get("missing_skills", []), (235, 100, 100))
        pdf.ln(3)

        # ── Recommendations ────────────────────────────────────────────
        recs = data.get("recommendations", [])
        if recs:
            section_header("💡  Skill Recommendations")
            for i, rec in enumerate(recs[:8], 1):
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(200, 220, 255)
                priority = rec.get("priority", "LOW")
                priority_color = {"HIGH": (235, 100, 100), "MEDIUM": (255, 180, 50), "LOW": (100, 200, 140)}
                pdf.cell(0, 6, f"  {i}. {rec.get('skill', '').title()}  [{priority}]",
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(140, 160, 190)
                url = rec.get("resource_url", "")
                if url:
                    pdf.cell(0, 5, f"     → {url}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.ln(1)
            pdf.ln(3)

        # ── Interview Questions ────────────────────────────────────────
        questions = data.get("interview_questions", [])
        if questions:
            pdf.add_page()
            section_header("❓  Generated Interview Questions")
            for i, q in enumerate(questions[:10], 1):
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(170, 200, 255)
                qtype = q.get("type", "Technical")
                qcat = q.get("category", "")
                pdf.cell(0, 6, f"  Q{i}. [{qtype} – {qcat}]",
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(220, 220, 220)
                pdf.multi_cell(0, 5, f"  {q.get('question', '')}",
                               new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.ln(2)

        # ── Footer note ────────────────────────────────────────────────
        pdf.set_fill_color(15, 17, 23)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 110, 130)
        pdf.ln(5)
        pdf.multi_cell(0, 5,
            "DISCLAIMER: This report is generated by an AI system and is intended to assist "
            "human decision-making only. Final hiring decisions should always involve human judgment.",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        buf = io.BytesIO()
        pdf.output(buf)
        buf.seek(0)
        return buf.read()

    except Exception as e:
        # Return a simple error PDF or bytes
        return b""
